### ISSUE TITLE
Allow version to be latest

### ISSUE THREAD

**Issue by bantl23** [bantl23/goreq#14]
Allow the required and banned version to be specified as the latest

For example:

```yaml
required:
  golang.org/x/mod: latest
banned:
  gopkg.in/yaml.v2:
    - latest
```
